import ICurrencies from '../constants/currencies';

export interface ISymbols {
  "CAD": { symbol: '' },
  "HKD": { symbol: '' },
  "ISK": { symbol: '' },
  "PHP": { symbol: '' },
  "DKK": { symbol: '' },
  "HUF": { symbol: '' },
  "CZK": { symbol: '' },
  "GBP": { symbol: '' },
  "RON": { symbol: '' },
  "SEK": { symbol: '' },
  "IDR": { symbol: '' },
  "INR": { symbol: '' },
  "BRL": { symbol: '' },
  "RUB": { symbol: '' },
  "HRK": { symbol: '' },
  "JPY": { symbol: '' },
  "THB": { symbol: '' },
  "CHF": { symbol: '' },
  "EUR": { symbol: '' },
  "MYR": { symbol: '' },
  "BGN": { symbol: '' },
  "TRY": { symbol: '' },
  "CNY": { symbol: '' },
  "NOK": { symbol: '' },
  "NZD": { symbol: '' },
  "ZAR": { symbol: '' },
  "USD": { symbol: '' },
  "MXN": { symbol: '' },
  "SGD": { symbol: '' },
  "AUD": { symbol: '' },
  "ILS": { symbol: '' },
  "KRW": { symbol: '' },
  "PLN": { symbol: '' }
}

export interface IExchangeRates {
  rates: {
    "CAD": number,
    "HKD": number,
    "ISK": number,
    "PHP": number,
    "DKK": number,
    "HUF": number,
    "CZK": number,
    "GBP": number,
    "RON": number,
    "SEK": number,
    "IDR": number,
    "INR": number,
    "BRL": number,
    "RUB": number,
    "HRK": number,
    "JPY": number,
    "THB": number,
    "CHF": number,
    "EUR": number,
    "MYR": number,
    "BGN": number,
    "TRY": number,
    "CNY": number,
    "NOK": number,
    "NZD": number,
    "ZAR": number,
    "USD": number,
    "MXN": number,
    "SGD": number,
    "AUD": number,
    "ILS": number,
    "KRW": number,
    "PLN": number
  };
  base: string;
  date: string;
}